comentarios:
    path:     /
    defaults: { _controller: "uniNmarcaJuntoBundle:comentarios:index" }

comentarios_show:
    path:     /{id}/show
    defaults: { _controller: "uniNmarcaJuntoBundle:comentarios:show" }

comentarios_new:
    path:     /new
    defaults: { _controller: "uniNmarcaJuntoBundle:comentarios:new" }

comentarios_create:
    path:     /create
    defaults: { _controller: "uniNmarcaJuntoBundle:comentarios:create" }
    requirements: { _method: post }

comentarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniNmarcaJuntoBundle:comentarios:edit" }

comentarios_update:
    path:     /{id}/update
    defaults: { _controller: "uniNmarcaJuntoBundle:comentarios:update" }
    requirements: { _method: post|put }

comentarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniNmarcaJuntoBundle:comentarios:delete" }
    requirements: { _method: post|delete }
