noticias:
    path:     /
    defaults: { _controller: "uniNmarcaJuntoBundle:noticias:index" }

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "uniNmarcaJuntoBundle:noticias:show" }

noticias_new:
    path:     /new
    defaults: { _controller: "uniNmarcaJuntoBundle:noticias:new" }

noticias_create:
    path:     /create
    defaults: { _controller: "uniNmarcaJuntoBundle:noticias:create" }
    requirements: { _method: post }

noticias_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniNmarcaJuntoBundle:noticias:edit" }

noticias_update:
    path:     /{id}/update
    defaults: { _controller: "uniNmarcaJuntoBundle:noticias:update" }
    requirements: { _method: post|put }

noticias_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniNmarcaJuntoBundle:noticias:delete" }
    requirements: { _method: post|delete }
